name: GitHub Pages

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps

    - uses: peaceiris/actions-gh-pages@v3
    - name: Deploy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/