name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
    - uses: actions/checkout@v4
    - name: Run doc
      run: cargo doc --no-deps
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
